/**
 * SF2e trait vocabularies pinned to src/scripts/config/traits.ts at
 * 3c9e8cb37c41039428b8d90f3fbc92f5c6c2657f.
 */
export const SF2E_NPC_ATTACK_TRAITS: Record<string, true> = {
    "abysium": true, "acid": true, "adamantine": true, "adjusted": true, "aeon": true, "agile": true, "air": true,
    "aiuvarin": true, "alchemical": true, "anadi": true, "analog": true, "android": true, "apex": true,
    "aphorite": true, "arc": true, "arcane": true, "archaic": true, "ardande": true, "area": true,
    "area-burst-10": true, "area-burst-15": true, "area-burst-20": true, "area-burst-25": true,
    "area-burst-30": true, "area-burst-5": true, "area-cone": true, "area-line": true, "artifact": true,
    "astrazoan": true, "athamaru": true, "attached": true, "attached-to-crossbow-or-firearm": true,
    "attached-to-shield": true, "attuned": true, "auditory": true, "automatic": true, "automaton": true,
    "awakened-animal": true, "azarketi": true, "backstabber": true, "backswing": true, "bantrid": true,
    "barathu": true, "beastkin": true, "bomb": true, "boost-1d10": true, "boost-1d12": true, "boost-1d4": true,
    "boost-1d6": true, "boost-1d8": true, "boost-2d10": true, "borai": true, "brace": true, "breakdown": true,
    "brenneri": true, "brutal": true, "bugbear": true, "capacity-2": true, "capacity-3": true, "capacity-4": true,
    "capacity-5": true, "caster": true, "catfolk": true, "centaur": true, "changeling": true, "climbing": true,
    "clockwork": true, "cobbled": true, "cold": true, "cold-iron": true, "combination": true, "concealable": true,
    "concentrate": true, "concussive": true, "conrasu": true, "consumable": true, "contemplative": true,
    "copaxi": true, "corpsefolk": true, "coshyco": true, "critical-brawling": true, "critical-corrosive": true,
    "critical-cryo": true, "critical-flame": true, "critical-fusion": true, "critical-knife": true,
    "critical-mental": true, "critical-plasma": true, "critical-shock": true, "critical-sonic": true,
    "curse": true, "cursed": true, "dawnsilver": true, "deadly-2d10": true, "deadly-2d12": true,
    "deadly-2d4": true, "deadly-2d6": true, "deadly-2d8": true, "deadly-3d10": true, "deadly-3d12": true,
    "deadly-3d4": true, "deadly-3d6": true, "deadly-3d8": true, "deadly-4d10": true, "deadly-4d12": true,
    "deadly-4d4": true, "deadly-4d6": true, "deadly-4d8": true, "deadly-d10": true, "deadly-d12": true,
    "deadly-d4": true, "deadly-d6": true, "deadly-d8": true, "death": true, "dhampir": true, "disarm": true,
    "disease": true, "divine": true, "djezet": true, "double-barrel": true, "dragonblood": true, "dragonet": true,
    "dragonhide": true, "dragonkin": true, "dreamweb": true, "dromaar": true, "duskwalker": true, "duskwood": true,
    "dwarf": true, "earth": true, "elebrian": true, "electricity": true, "elf": true, "emotion": true,
    "entu-colony": true, "expend-1": true, "expend-10": true, "expend-2": true, "expend-5": true,
    "extradimensional": true, "fatal-aim-d10": true, "fatal-aim-d12": true, "fatal-d10": true, "fatal-d12": true,
    "fatal-d8": true, "fear": true, "fetchling": true, "finesse": true, "fire": true, "fleshwarp": true,
    "fonqugon": true, "force": true, "forceful": true, "formian": true, "fortune": true, "free-hand": true,
    "fungus": true, "ganzi": true, "gap-touched": true, "geniekin": true, "gfolian": true, "ghoran": true,
    "gnome": true, "goblin": true, "goloma": true, "grapple": true, "grenade": true, "grisantian-pelt": true,
    "halfling": true, "hampering": true, "healing": true, "hobgoblin": true, "holy": true, "human": true,
    "hungerseed": true, "ijtikri": true, "ikeshti": true, "illusion": true, "impulse": true, "incorporeal": true,
    "infused": true, "inhaled": true, "injection": true, "intelligent": true, "inubrix": true, "invested": true,
    "izalguun": true, "jotunborn": true, "jousting-d10": true, "jousting-d4": true, "jousting-d6": true,
    "jousting-d8": true, "kalo": true, "kasatha": true, "kashrishi": true, "keep-stone": true, "khizar": true,
    "kholo": true, "kickback": true, "kitsune": true, "kobold": true, "lashunta": true, "leshy": true,
    "light": true, "linguistic": true, "lizardfolk": true, "madrosarai": true, "magical": true, "maraquoi": true,
    "mental": true, "merfolk": true, "metal": true, "minotaur": true, "modular": true, "monk": true,
    "moyishuu": true, "mythic": true, "naari": true, "nagaji": true, "nephilim": true, "nonlethal": true,
    "noqual": true, "novian": true, "occult": true, "olfactory": true, "orc": true, "oread": true,
    "orichalcum": true, "orocoran": true, "osharu": true, "pahtra": true, "parry": true, "peachwood": true,
    "plant": true, "poison": true, "poppet": true, "powered": true, "primal": true, "prismeni": true,
    "professional-computers": true, "professional-crafting": true, "professional-deception": true,
    "professional-performance": true, "propulsive": true, "radiation": true, "ranged-shove": true,
    "ranged-trip": true, "ratfolk": true, "raxilite": true, "razing": true, "reach": true, "reach-0": true,
    "reach-10": true, "reach-100": true, "reach-1000": true, "reach-120": true, "reach-15": true, "reach-20": true,
    "reach-200": true, "reach-25": true, "reach-30": true, "reach-40": true, "reach-50": true, "reach-60": true,
    "recovery": true, "reflection": true, "relic": true, "reload-0": true, "reload-1": true, "reload-1-min": true,
    "reload-2": true, "repeating": true, "resonant": true, "ryphorian": true, "saggorak": true, "samsaran": true,
    "sanctified": true, "sarangay": true, "sarcesian": true, "scatter-10": true, "scatter-15": true,
    "scatter-20": true, "scatter-5": true, "scrying": true, "shadow": true, "shirren": true, "shisk": true,
    "shobhad": true, "shoony": true, "shove": true, "siccatite": true, "silver": true, "sisterstone": true,
    "sisterstone-dusk": true, "sisterstone-scarlet": true, "skeleton": true, "skittermander": true,
    "sloughstone": true, "solarian": true, "sonic": true, "sovereign-steel": true, "spirit": true, "splash": true,
    "sprite": true, "staff": true, "strix": true, "suli": true, "surki": true, "sweep": true, "sylph": true,
    "talos": true, "talphi": true, "tanuki": true, "tearing": true, "tech": true, "teleportation": true,
    "tengu": true, "tethered": true, "thought": true, "thrown": true, "thrown-10": true, "thrown-100": true,
    "thrown-15": true, "thrown-20": true, "thrown-200": true, "thrown-30": true, "thrown-40": true,
    "thrown-50": true, "thrown-60": true, "thrown-80": true, "time": true, "tracking-1": true, "tracking-2": true,
    "tracking-3": true, "training": true, "trip": true, "tripkee": true, "trox": true, "twin": true,
    "two-hand-d10": true, "two-hand-d12": true, "two-hand-d6": true, "two-hand-d8": true, "unarmed": true,
    "undine": true, "unholy": true, "unwieldy": true, "upgrade": true, "urog": true, "vanara": true,
    "vehicular": true, "venomous": true, "versatile-acid": true, "versatile-b": true, "versatile-cold": true,
    "versatile-electricity": true, "versatile-fire": true, "versatile-force": true, "versatile-mental": true,
    "versatile-p": true, "versatile-poison": true, "versatile-s": true, "versatile-sonic": true,
    "versatile-spirit": true, "versatile-vitality": true, "versatile-void": true, "vesk": true, "vishkanya": true,
    "visual": true, "vitality": true, "vlaka": true, "void": true, "volley-20": true, "volley-30": true,
    "volley-50": true, "volley-60": true, "wand": true, "warpglass": true, "water": true, "wayang": true,
    "wood": true, "worlanisi": true, "xenometric-android": true, "yaksha": true, "yaoguai": true,
};

export const SF2E_CREATURE_TRAITS: Record<string, true> = {
    "aberration": true, "acid": true, "aeon": true, "aesir": true, "agathion": true, "air": true, "aiuvarin": true,
    "alchemical": true, "amphibious": true, "anadi": true, "android": true, "angel": true, "animal": true, "anugobu": true,
    "aphorite": true, "aquatic": true, "arcane": true, "archon": true, "ardande": true, "astral": true, "astrazoan": true,
    "asura": true, "athamaru": true, "automaton": true, "awakened-animal": true, "azarketi": true, "azata": true, "bantrid": true,
    "barathu": true, "beast": true, "beastkin": true, "blight": true, "boggard": true, "borai": true, "brenneri": true,
    "bugbear": true, "caligni": true, "catfolk": true, "celestial": true, "centaur": true, "changeling": true, "charau-ka": true,
    "clockwork": true, "cold": true, "conrasu": true, "construct": true, "contemplative": true, "copaxi": true, "corpsefolk": true,
    "coshyco": true, "cosmic": true, "couatl": true, "daemon": true, "darvakka": true, "demon": true, "dero": true,
    "devil": true, "dhampir": true, "dinosaur": true, "div": true, "divine": true, "dragon": true, "dragonblood": true,
    "dragonet": true, "dragonkin": true, "dream": true, "drift": true, "dromaar": true, "drow": true, "duergar": true,
    "duskwalker": true, "dwarf": true, "earth": true, "eidolon": true, "elebrian": true, "electricity": true, "elemental": true,
    "elf": true, "entu-colony": true, "ethereal": true, "experiment": true, "fetchling": true, "fey": true, "fiend": true,
    "fire": true, "fleshwarp": true, "fonqugon": true, "force": true, "formian": true, "fungus": true, "ganzi": true,
    "gap-touched": true, "genie": true, "geniekin": true, "gfolian": true, "ghoran": true, "ghost": true, "ghoul": true,
    "ghul": true, "giant": true, "gigas": true, "girtablilu": true, "gnome": true, "goblin": true, "golem": true,
    "goloma": true, "graveknight": true, "gremlin": true, "grioth": true, "hag": true, "halfling": true, "hantu": true,
    "herald": true, "hobgoblin": true, "holy": true, "hryngar": true, "human": true, "humanoid": true, "hungerseed": true,
    "ijtikri": true, "ikeshti": true, "illusion": true, "incorporeal": true, "inevitable": true, "izalguun": true, "jinsul": true,
    "jotunborn": true, "kaiju": true, "kalo": true, "kami": true, "kasatha": true, "kashrishi": true, "khizar": true,
    "kholo": true, "kitsune": true, "kobold": true, "kothama": true, "kovintus": true, "kucharn": true, "lashunta": true,
    "leshy": true, "light": true, "lilu": true, "lizardfolk": true, "locathah": true, "madrosarai": true, "maftet": true,
    "maraquoi": true, "mental": true, "merfolk": true, "metal": true, "mindless": true, "minion": true, "minotaur": true,
    "monitor": true, "morlock": true, "mortic": true, "moyishuu": true, "mummy": true, "munavri": true, "mutant": true,
    "mythic": true, "naari": true, "nagaji": true, "nephilim": true, "nindoru": true, "novian": true, "nymph": true,
    "occult": true, "oni": true, "ooze": true, "orc": true, "oread": true, "orocoran": true, "osharu": true,
    "paaridar": true, "pahtra": true, "palinthanos": true, "persona-flirt": true, "persona-guardian": true, "persona-leader": true, "persona-scholar": true,
    "persona-scoundrel": true, "persona-underdog": true, "persona-warrior": true, "persona-wildcard": true, "petitioner": true, "phantom": true, "plant": true,
    "poison": true, "poppet": true, "primal": true, "prismeni": true, "protean": true, "psychopomp": true, "qlippoth": true,
    "rakshasa": true, "ratfolk": true, "raxilite": true, "reflection": true, "robot": true, "ryphorian": true, "sahkil": true,
    "samsaran": true, "sarangay": true, "sarcesian": true, "sea-devil": true, "sedacthy": true, "serpentfolk": true, "seugathi": true,
    "shabti": true, "shade": true, "shadow": true, "shirren": true, "shisk": true, "shobhad": true, "shoony": true,
    "siktempora": true, "skeleton": true, "skelm": true, "skittermander": true, "skulk": true, "sonic": true, "soulbound": true,
    "spectra": true, "spirit": true, "sporeborn": true, "spriggan": true, "sprite": true, "stheno": true, "strix": true,
    "suli": true, "summoned": true, "surki": true, "swarm": true, "sylph": true, "talos": true, "talphi": true,
    "tane": true, "tanggal": true, "tanuki": true, "tech": true, "tengu": true, "time": true, "titan": true,
    "tripkee": true, "troll": true, "troop": true, "trox": true, "undead": true, "undine": true, "unholy": true,
    "urdefhan": true, "urog": true, "vampire": true, "vanara": true, "velstrac": true, "vesk": true, "vishkanya": true,
    "vitality": true, "vlaka": true, "void": true, "water": true, "wayang": true, "werecreature": true, "wight": true,
    "wild-hunt": true, "wood": true, "worlanisi": true, "wraith": true, "wraithvine": true, "wyrwood": true, "xenometric-android": true,
    "xulgath": true, "yaksha": true, "yaoguai": true, "zombie": true,
};

export const SF2E_ACTION_TRAITS: Record<string, true> = {
    "acid": true, "additive": true, "additive1": true, "additive2": true, "additive3": true, "aftermath": true,
    "agile": true, "air": true, "aiuvarin": true, "alchemical": true, "alchemist": true, "amp": true,
    "anadi": true, "anchoring": true, "android": true, "animist": true, "aphorite": true, "apparition": true,
    "arcane": true, "archetype": true, "ardande": true, "area": true, "artifact": true, "astrazoan": true,
    "athamaru": true, "attack": true, "attuned": true, "auditory": true, "aura": true, "automatic": true,
    "automaton": true, "awakened-animal": true, "azarketi": true, "backswing": true, "bantrid": true,
    "barathu": true, "barbarian": true, "bard": true, "beast": true, "beastkin": true, "borai": true,
    "bottled-breath": true, "brandish": true, "bravado": true, "brenneri": true, "bugbear": true, "calling": true,
    "cantrip": true, "catalyst": true, "catfolk": true, "centaur": true, "certain-kill": true, "champion": true,
    "changeling": true, "circus": true, "class": true, "cleric": true, "clockwork": true, "coagulant": true,
    "cold": true, "commander": true, "composite": true, "composition": true, "concentrate": true, "conrasu": true,
    "consecration": true, "consumable": true, "contact": true, "contemplative": true, "contingency": true,
    "copaxi": true, "corpsefolk": true, "coshyco": true, "curse": true, "cursebound": true, "cursed": true,
    "cycle": true, "darkness": true, "death": true, "dedication": true, "destiny": true, "detection": true,
    "deviant": true, "dhampir": true, "directive": true, "disease": true, "disharmony": true, "divine": true,
    "downtime": true, "dragonblood": true, "dragonet": true, "dragonkin": true, "dream": true, "dromaar": true,
    "drug": true, "druid": true, "duskwalker": true, "dwarf": true, "earth": true, "eidolon": true,
    "elebrian": true, "electricity": true, "elf": true, "elixir": true, "emotion": true, "entu-colony": true,
    "envoy": true, "esoterica": true, "evolution": true, "exemplar": true, "expandable": true, "exploration": true,
    "extradimensional": true, "fear": true, "fetchling": true, "fey": true, "fighter": true, "finisher": true,
    "fire": true, "fleshwarp": true, "flourish": true, "focus": true, "fonqugon": true, "force": true,
    "forceful": true, "formian": true, "fortune": true, "fulu": true, "fungus": true, "gadget": true,
    "ganzi": true, "gap-touched": true, "general": true, "geniekin": true, "gfolian": true, "ghoran": true,
    "gnome": true, "goblin": true, "goloma": true, "gravity": true, "guardian": true, "gunslinger": true,
    "halfling": true, "healing": true, "hex": true, "hobgoblin": true, "holy": true, "human": true,
    "hungerseed": true, "ijtikri": true, "ikeshti": true, "ikon": true, "illusion": true, "impulse": true,
    "incapacitation": true, "incarnate": true, "incorporeal": true, "infused": true, "infusion": true,
    "ingested": true, "inhaled": true, "injury": true, "inventor": true, "investigator": true, "izalguun": true,
    "jotunborn": true, "kalo": true, "kasatha": true, "kashrishi": true, "khizar": true, "kholo": true,
    "kineticist": true, "kitsune": true, "kobold": true, "lashunta": true, "leshy": true, "lfan": true,
    "light": true, "lineage": true, "linguistic": true, "litany": true, "lizardfolk": true, "lozenge": true,
    "madrosarai": true, "magical": true, "magus": true, "manifestation": true, "manipulate": true,
    "maraquoi": true, "mechanical": true, "mental": true, "merfolk": true, "metal": true, "mindshift": true,
    "minotaur": true, "misfortune": true, "missive": true, "modification": true, "monk": true, "morph": true,
    "move": true, "moyishuu": true, "multiclass": true, "mutagen": true, "mystic": true, "mythic": true,
    "naari": true, "nagaji": true, "nephilim": true, "nonlethal": true, "novian": true, "oath": true,
    "occult": true, "oil": true, "olfactory": true, "operative": true, "oracle": true, "orc": true, "oread": true,
    "orocoran": true, "osharu": true, "overflow": true, "pahtra": true, "pervasive-magic": true, "plant": true,
    "poison": true, "polymorph": true, "poppet": true, "possession": true, "potion": true, "precious": true,
    "prediction": true, "press": true, "primal": true, "prismeni": true, "processed": true, "propulsive": true,
    "psyche": true, "psychic": true, "radiation": true, "rage": true, "ranger": true, "ratfolk": true,
    "raxilite": true, "reach": true, "reckless": true, "reflection": true, "reincarnated": true,
    "revelation": true, "rogue": true, "ryphorian": true, "samsaran": true, "sanctified": true, "sarangay": true,
    "sarcesian": true, "scroll": true, "scrying": true, "secret": true, "serum": true, "shadow": true,
    "shirren": true, "shisk": true, "shobhad": true, "shoony": true, "skeleton": true, "skill": true,
    "skittermander": true, "sleep": true, "snare": true, "social": true, "solarian": true, "soldier": true,
    "sonic": true, "sorcerer": true, "spellgun": true, "spellshape": true, "spellshot": true, "spirit": true,
    "splash": true, "sprite": true, "stamina": true, "stance": true, "strix": true, "structure": true,
    "subtle": true, "suli": true, "summon": true, "summoned": true, "summoner": true, "suppressed": true,
    "surki": true, "swashbuckler": true, "sweep": true, "sylph": true, "tactic": true, "talisman": true,
    "talos": true, "talphi": true, "tandem": true, "tanuki": true, "tea": true, "tech": true,
    "teleportation": true, "tengu": true, "thaumaturge": true, "thrown": true, "time": true, "transcendence": true,
    "transfer": true, "trap": true, "traversal": true, "trial": true, "tripkee": true, "trox": true,
    "true-name": true, "undine": true, "unholy": true, "unstable": true, "urog": true, "vanara": true,
    "vesk": true, "vigilante": true, "virulent": true, "vishkanya": true, "visual": true, "vitality": true,
    "vlaka": true, "void": true, "volley-20": true, "volley-30": true, "volley-50": true, "volley-60": true,
    "wand": true, "wandering": true, "water": true, "wayang": true, "whetstone": true, "witch": true,
    "witchwarper": true, "wizard": true, "wood": true, "worlanisi": true, "xenometric-android": true,
    "yaksha": true, "yaoguai": true, "zone": true,
};
